making sure that tests work in local appengine as well (call ./acre appengine-prepare-tests before calling ./acre test)

diff --git a/bin/testng b/bin/testng
--- a/bin/testng
+++ b/bin/testng
@@ -48,6 +48,16 @@ else
     $ECHO "PASSED"
 fi
 
+$ECHO -n "CHECK: local tests are present... "
+RESP=`curl -s -S -m 5  http://qa.dev.${ACRE_HOST_BASE}:$ACRE_PORT/write 2> /dev/null | grep "ok"`
+if [ -z "$RESP" ]; then
+    $ECHO "FAILED"
+    $ECHO "FATAL: the required local tests don't seem to be available"
+    exit 1
+else
+    $ECHO "PASSED"
+fi
+
 bin/freebase_check
 if [ $? -ne 0 ]; then
     exit 1
