making sure that tests work in local appengine as well (call ./acre appengine-prepare-tests before calling ./acre test)

diff --git a/trunk/bin/test b/trunk/bin/test
--- a/trunk/bin/test
+++ b/trunk/bin/test
@@ -55,6 +55,16 @@ else
     $ECHO "PASSED"
 fi
 
+$ECHO -n "CHECK: local tests are present... "
+RESP=`curl -s -S -m 5  http://api.qatests.apps.freebase.dev.${ACRE_HOST_BASE}:$ACRE_PORT/request 2> /dev/null | grep "api.qatests.apps.freebase"`
+if [ -z "$RESP" ]; then
+    $ECHO "FAILED"
+    $ECHO "FATAL: the required local tests don't seem to be available (did you run './acre appeditor-prepare-tests' yet?)"
+    exit 1
+else
+    $ECHO "PASSED"
+fi
+
 bin/freebase_check
 if [ $? -ne 0 ]; then
     exit 1
